argo-workflows:
  singleNamespace: false
  controller:
    workflowNamespaces:
      - the-grid-synthetics
  workflow:
    serviceAccount:
      name: playwright-synthetics-sa
  server:
    authModes:
      - server
