apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: argo-workflows
spec:
  project: default
  source:
    repoURL: https://github.com/dylanjustice/the-grid
    targetRevision: HEAD
    path: gitops/workloads/argo-workflows
    helm:
      releaseName: argo-workflows
      skipCrds: false
  destination:
    name: in-cluster
    namespace: the-grid-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m