---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cache.the-grid.io
  resources:
  - synthetictestruns
  - synthetictests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.the-grid.io
  resources:
  - synthetictestruns/finalizers
  - synthetictests/finalizers
  verbs:
  - update
- apiGroups:
  - cache.the-grid.io
  resources:
  - synthetictestruns/status
  - synthetictests/status
  verbs:
  - get
  - patch
  - update
