{{- $serviceAccountName := include "the-grid-playwright-synthetics.serviceAccountName" . -}}
{{- range $workflow := .Values.workflows }}
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: {{ $workflow.name | replace " " "-" | lower }}
spec:
  entrypoint: {{ $workflow.entrypoint }}
  {{- if $.Values.serviceAccount.create }}
  serviceAccountName: {{ $serviceAccountName }}
  {{- end }}
  schedules:
    - {{ $workflow.schedule }}
  templates:
    {{ toYaml $workflow.templates | nindent 4 }}
{{- end }}
